# Generated by Django 2.1.3 on 2018-11-28 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perro',
            name='imageUrl',
            field=models.ImageField(blank=True, upload_to='image'),
        ),
    ]
