# Generated by Django 2.1.4 on 2018-12-09 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_perro_imageurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.IntegerField()),
                ('ciudad', models.CharField(max_length=25)),
                ('nombre', models.CharField(max_length=45)),
                ('direccion', models.CharField(max_length=100)),
                ('comuna', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='orden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clienteAtendido', models.CharField(max_length=45)),
                ('Fecha', models.DateTimeField(blank=True, null=True)),
                ('horaInicio', models.DateTimeField(blank=True, null=True)),
                ('horaTermino', models.DateTimeField(blank=True, null=True)),
                ('idAscensor', models.IntegerField()),
                ('modeloAscensor', models.CharField(max_length=40)),
                ('fallasDetectadas', models.TextField()),
                ('reparacionesEfectuadas', models.TextField()),
                ('piezasCambiadas', models.CharField(max_length=200)),
                ('nombreTrabajador', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='tecnico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreTecnico', models.CharField(max_length=45)),
                ('ClienteAsignado', models.CharField(max_length=45)),
            ],
        ),
        migrations.DeleteModel(
            name='perro',
        ),
    ]
